### ISSUE TITLE
Roadmap v1.0.0-alpha

### ISSUE THREAD

**Issue by cyrildewit** [cyrildewit/java-game-assignment-pong#3]
### Specification

- [x] The game must consist of the following entities: `Paddle`, `Ball`, `Wall`, `Goal` and `Net`. They don't have to interact with eachother (collision handling or offscreen blocking) and their appearance should look good. It should also be located at the right location.
- [x] The `KeyManager` class should be renamed to `Input` and it should take care of other events as well like mouse buttons, mouse wheel and mouse movement.
- [x] The ID enum class should be refactored into `EntityType`.
