### ISSUE TITLE
Roadmap v1.0.0-alpha.2

### ISSUE THREAD

**Issue by cyrildewit** [cyrildewit/java-game-assignment-pong#5]
## Specification

- [x] The `Paddle` entity should move up or down based on keyboard input. The left paddle should be controlled using `W` and `S` and the right paddle should be controlled using `UP` and `DOWN`.
- [x] The `Paddle` entity shouldn't go higher or lower than the canvas itself. This can be achieved by checking for a collision with a `Wall` entity.
- [x] The `Ball` entity should bounce when it collides with a `Wall` entity.
- [x] The `Ball` entity should bounce when it collides with a `Paddle` entity.
- [x] When `Ball` entity collides with a `Goal` entity, a message should be printed in the console.

- ~The `Ball` entity should move in a random direction.~
