### ISSUE TITLE
Roadmap v1.0.0-alpha.3

### ISSUE THREAD

**Issue by cyrildewit** [cyrildewit/java-game-assignment-pong#8]
## Specification

- [x] When the `Ball` entity touches a `Goal` entity, a point should be given to the player who scored.
- [x] The `PlayerScore` entity should print the score on the screen.
- [x] The font of the `PlayerScore` entity should be ['Bitfont'](http://www.mattlag.com/bitfonts/)
- [x] The `Ball` entity should be respawned when a goal has been made.
- [x] After the `Ball` has been respawned, it should move in a random direction to the other side of the player who made the point.
- [x] The speed of the `Paddle` entity should be a little bit faster.
- [x] The player who last scored shouldn't receive the ball as first.
- [x] After one player scored 11 points, the game should be stopped.
